In [16]:
import csv
import numpy as np
import pandas as pd
with open('dashboard_database.csv', mode='r', encoding='utf-8') as db:
    result = []
    reader = pd.read_csv(db)
reader
#    print(db.head(10))

,TransactionID,TransactionAmt,TransactionDT,card1,card4,isFraud
0,3663549,31.950,18403224,10409,visa,0.055130
1,3663550,49.000,18403263,4272,visa,0.036125
2,3663551,171.000,18403310,4476,visa,0.064595
3,3663552,284.950,18403310,10989,visa,0.066475
4,3663553,67.950,18403317,18018,mastercard,0.043608
...,...,...,...,...,...,...
506686,4170235,94.679,34214279,13832,mastercard,0.432119
506687,4170236,12.173,34214287,3154,mastercard,0.091326
506688,4170237,49.000,34214326,16661,visa,0.071427
506689,4170238,202.000,34214337,16621,mastercard,0.072990
506690,4170239,24.346,34214345,5713,visa,0.082608

In [25]:
db = pd.read_csv('dashboard_database.csv')
db.head(10)
card_num = 10409
x = db[db["card1"] == card_num]
x

        TransactionID  TransactionAmt  TransactionDT  card1 card4   isFraud
0             3663549           31.95       18403224  10409  visa  0.055130
1990          3665539          226.00       18484558  10409  visa  0.757293
8252          3671801          554.00       18652140  10409  visa  0.219380
10030         3673579           35.95       18721473  10409  visa  0.032089
24427         3687976           82.00       19237201  10409  visa  0.171240
...               ...             ...            ...    ...   ...       ...
436237        4099786           57.95       32804531  10409  visa  0.037648
477706        4141255           57.95       33599718  10409  visa  0.029997
485828        4149377           75.00       33700948  10409  visa  0.264721
488244        4151793          117.95       33751935  10409  visa  0.062164
499740        4163289           50.00       34022363  10409  visa  0.072001

[75 rows x 6 columns]